### ISSUE TITLE
go build github.com/ugorji/go/codec: no Go files in

### ISSUE THREAD

**Issue by piLinux** [gin-contrib/authz#11]
https://github.com/gin-contrib/authz/blob/1fb3afa6ee8a42d2dda163c16ee56091bb3cf765/go.mod#L17

Most probably you wanted to refer to this?
https://github.com/ugorji/go-codec

**Comment by hsluoyz** [comment]
Yes. That repo needs to be renamed. Can you make a PR and update our go.mod file?

**Comment by piLinux** [comment]
It seems there is no need to update the `go.mod` file. Before importing the repos, `GO111MODULE` should be set to `auto` or `off`.

I tried to import ugorji/go-codec by `go get github.com/ugorji/go-codec` and it didn't work. Later I figured out that they changed the repo path but kept the same import path.

[ugorji/go-codec/go.mod](https://github.com/ugorji/go-codec/blob/c8f752a850d09ea4f08812add5b1cb569ddc0c2f/go.mod#L1)

[ugorji/go-codec/codec/0_importpath.go](https://github.com/ugorji/go-codec/blob/c8f752a850d09ea4f08812add5b1cb569ddc0c2f/codec/0_importpath.go#L4)

So everything should be fine as it was before. I am closing this issue. And thank you @hsluoyz for your prompt response :)

**Comment by shrishankit** [comment]
@piLinux what did you do resolve the issue?

**Comment by piLinux** [comment]
> @piLinux what did you do to resolve the issue?

With the default settings, it should work perfectly. If not, 
set `GO111MODULE` to `auto`.

`export GO111MODULE=auto`

The above solution is for Linux. I didn't try it on Windows or Mac.
