### ISSUE TITLE
"go get ..." results in error

### ISSUE THREAD

**Issue by dadav** [gin-contrib/authz#12]
I want to install this package with:

"go get github.com/gin-contrib/authz"

but it returns:

```shell
# github.com/gin-contrib/authz
authz/authz.go:43:2: too many arguments to return
        have (bool, error)
        want (bool)
```

```shell
$ go version
go version go1.12.7 linux/amd64
```

**Comment by hsluoyz** [comment]
Hi @dadav , have fixed in: https://github.com/gin-contrib/authz/commit/b2abe43e162e6804ce4173b615dc545710e4871f
