### ISSUE TITLE
[Question] Can you please provide an example?

### ISSUE THREAD

**Issue by MushiTheMoshi** [gin-contrib/authz#31]
Hi there,

Looks great, though I am not too sure how to implement it, is there a chance you could add a full example how to implement in a gin app?

Thanks in advance,
Julio

**Comment by tomriddle1234** [comment]
Second this, need an example use this with your gin-jwt

**Comment by hsluoyz** [comment]
@JalinWang

**Comment by qrhfz** [comment]
> I don't get you. What do you want to know?

@JalinWang Curse of Knowledge aye?

**Comment by hsluoyz** [comment]
@MushiTheMoshi @tomriddle1234 @qrhfz see: https://github.com/casbin/gin-casbin-example
