### ISSUE TITLE
BasicAuthorizer object recreated on every request

### ISSUE THREAD

**Issue by Neopallium** [gin-contrib/authz#6]
I think `BasicAuthorizer` should be created outside of the closure.  Since the closure is called for every request.
https://github.com/gin-contrib/authz/blob/13cec1463825f85fc3ed48da7fd9e838fe3a64a6/authz.go#L15-L17

**Comment by hsluoyz** [comment]
Looks good to me. Can you make a PR about it?

**Comment by Neopallium** [comment]
PR created #7

**Comment by hsluoyz** [comment]
Merged. Thanks for the contribution.
